CREATE DATABASE DBPROJETOVET;
USE DBPROJETOVET;

CREATE TABLE tbplano (
CodPlano INT PRIMARY KEY AUTO_INCREMENT,
Nome VARCHAR(40) NOT NULL,
Idade INT NOT NULL,
Porte VARCHAR(7) NOT NULL,
Raca VARCHAR(40) NOT NULL,
Plano VARCHAR(15) NOT NULL,
Tipo VARCHAR(10) NOT NULL
);

DESCRIBE tbplano;